---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/ctlptl version
    register: ctlptl_test_output
  - name: ctlptl version
    debug:
      msg: '{{ ctlptl_test_output.stdout }}'
